import classNames from "classnames";
import styles from "./kapa.module.css";

const Kapa = () => {
  let kapaWidget = (
    <section className={styles.AskButtonContainer}>
      <section id="kapa-ai" className={styles.AskButton}>
        <i className={styles.AskIcon}>question_mark</i>
        <p className={styles.AskText}>Ask AI</p>
      </section>
      <script
        src="https://widget.kapa.ai/kapa-widget.bundle.js"
        data-website-id="e81c2b35-6c03-4576-a56c-3c825f866e06"
        data-project-name="Streamlit"
        data-project-color="#000000"
        data-project-logo="https://docs.streamlit.io/logo.svg"
        data-modal-disclaimer="
              This is an LLM-powered chatbot for Streamlit with access to the following
              Streamlit sources: (i) Documentation (docs.streamlit.io/); (ii) forum posts
              (discuss.streamlit.io/); and (iii) GitHub Issues (github.com/streamlit/streamlit).
              Answers are generated by AI and may be inaccurate, inappropriate, inefficient,
              or biased. Decisions based on such outputs should have human oversight and
              review processes to ensure they are safe, accurate, and suitable for your
              intended use.
              
              Do not enter any private, sensitive, personal,
              or regulated data. If personally identifiable information is detected,
              the chatbot will not generate an answer and you will be asked to enter
              your prompt again."
        data-button-hide="true"
        data-modal-override-open-id="kapa-ai"
        data-modal-lock-scroll="false"
        data-modal-border-radius="6px"
        data-modal-image-height="18px"
      ></script>
    </section>
  );

  return kapaWidget;
};

export default Kapa;
