backend:
  name: git-gateway
  branch: main
media_folder: public/img
public_folder: /img
collections:
  - name: "pages"
    label: "Site"
    files:
      - label: "Home"
        name: "home"
        file: "content/index.md"
        fields:
          - label: Title
            name: title
            widget: string
          - label: Body
            name: body
            widget: markdown
            minimal: true
          - label: Features
            name: features
            widget: list
            summary: "{{fields.title}}"
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Body, name: body, widget: string }
              - {
                  label: URL,
                  name: url,
                  widget: string,
                  hint: "Should be a full url (https://www.example/)",
                }
              - {
                  label: Color,
                  name: color,
                  widget: select,
                  options:
                    [
                      "violet-70",
                      "orange-70",
                      "blue-70",
                      "red-70",
                      "yellow-70",
                      "green-70",
                      "b-g-70",
                      "l-blue-70",
                      "gray-70",
                    ],
                }
              - {
                  label: Image,
                  name: image,
                  widget: image,
                  hint: "Takes precedent over an icon, if set.",
                  required: false,
                }
              - {
                  label: Icon,
                  name: icon,
                  widget: string,
                  hint: "Must be the name (like_this) of a Material Icon. Should be an SVG.",
                  required: false,
                }
          - label: "What's New"
            name: whats_new
            widget: list
            summary: "{{fields.title}}"
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Body, name: body, widget: string }
              - {
                  label: URL,
                  name: url,
                  widget: string,
                  hint: "Should be a full url (https://www.example/)",
                }
              - {
                  label: Icon,
                  name: icon,
                  widget: string,
                  hint: "Must be the name (like_this) of a Material Icon.",
                  required: false,
                }
              - {
                  label: Image,
                  name: image,
                  widget: image,
                  hint: "Takes precedent over an icon, if set. Should be an SVG.",
                  required: false,
                }
          - label: News
            name: news
            widget: list
            summary: "{{fields.publish_date}} - {{fields.title}}"
            fields:
              - { label: "Date", name: publish_date, widget: string }
              - { label: Title, name: title, widget: string }
              - { label: Body, name: body, widget: text }
              - {
                  label: URL,
                  name: url,
                  widget: string,
                  hint: "Should be a full url (https://www.example/)",
                }
          - label: Next Page
            name: next
            widget: relation
            collection: "contents"
            value_field: "{{slug}}"
            search_fields: ["title", "category"]
            display_fields: ["{{category}} / {{title}}"]
      - name: "menu"
        label: "Menu"
        create: true
        file: "content/menu.md"
        fields:
          - label: Site Menu
            name: site_menu
            widget: list
            summary: "{{fields.category}}"
            fields:
              - {
                  label: Node,
                  name: category,
                  widget: string,
                  hint: "Use Parent / Child / Child format, with the last element acting as the item title.",
                }
              - {
                  label: URL,
                  name: url,
                  widget: string,
                  hint: "Should be either a full url (https://www.example/) or an absolute URL (/like/this)",
                }
              - {
                  label: Color,
                  name: color,
                  widget: select,
                  options:
                    [
                      "violet-70",
                      "orange-70",
                      "blue-70",
                      "red-70",
                      "yellow-70",
                      "green-70",
                      "b-g-70",
                      "l-blue-70",
                      "gray-70",
                    ],
                  required: false,
                }
              - {
                  label: Icon,
                  name: icon,
                  widget: string,
                  hint: "Must be the name (like_this) of a Material Icon.",
                  required: false,
                }
              - {
                  label: Deprecated?,
                  name: isDeprecated,
                  widget: boolean,
                  hint: "Marks the parameter as deprecated in the menu",
                  required: false,
                  default: false,
                }
  - name: "contents"
    label: "Documentation"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - label: Title
        name: title
        widget: string
      - label: Page Catgeory
        name: category
        widget: string
        hint: "Categories should be separated by back slashes (Parent / Child / Child)"
      - label: Body
        name: body
        widget: markdown
        modes: ["raw"]
      - label: Next Page
        name: next
        widget: relation
        collection: "contents"
        value_field: "{{slug}}"
        search_fields: ["title", "category"]
        display_fields: ["{{category}} / {{title}}"]
