# Docker Compose version
version: "3.3"
services:
  python:
    build:
      context: ../
      dockerfile: python/Dockerfile
    image: streamlit-docstring-generator:latest
    command: python build.py
    volumes:
      - ../python:/docs
