[server]
enableStaticServing = true

[[theme.fontFaces]]
family = "Poppins"
url = "app/static/Poppins-Regular.ttf"
style="normal"
weight="400"

[[theme.fontFaces]]
family = "Poppins"
url = "app/static/Poppins-Italic.ttf"
style="italic"
weight="400"

[[theme.fontFaces]]
family = "Poppins"
url = "app/static/Poppins-Bold.ttf"
style="normal"
weight="700"

[[theme.fontFaces]]
family = "Poppins"
url = "app/static/Poppins-BoldItalic.ttf"
style="italic"
weight="700"

[theme]
base = "dark"
baseFontSize = 15
primaryColor = "#1ED760"
backgroundColor = "#121212"
secondaryBackgroundColor = "#333333"
textColor = "#FFFFFF"
linkColor = "#9D9D9D"
borderColor = "#7F7F7F"
showWidgetBorder = false
baseRadius = "0.3rem"
font = "Poppins"

[theme.sidebar]
backgroundColor = "#000000"
secondaryBackgroundColor = "#333333"
borderColor = "#696969"